[versions]
kotlinpoet = "2.1.0"
kotlin-gradle-plugin = "2.3.10"
gradle-pluginPublish = "2.0.0"

[libraries]
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlin-scripting-common = { module = "org.jetbrains.kotlin:kotlin-scripting-common" }
kotlin-scripting-jvm = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm" }
kotlin-scripting-jvm-host = { module = "org.jetbrains.kotlin:kotlin-scripting-jvm-host" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginPublish" }
